[package]
name = "godot-blackjack"
version = "0.1.0"
authors = ["Eric Smith <paytonrules@gmail.com>"]
edition = "2018"

[dependencies]
gdnative = "0.9.0-preview.0"
blackjack = { path = "../blackjack" }
im = "15.0.0"
thiserror = "1.0"

[lib]
crate-type = ["cdylib"]
